#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to a YouTube video with a 301 status code.
# Update package list
sudo apt-get update

# Install Nginx if not already installed
sudo apt-get install -y nginx

# Create a new Nginx configuration file
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.nginx-debian.html;

    server_name emerance1.tech;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
